{
 "title": "POBR",
 "time": { "from": "2012-12-01T12:30:00.000Z", "to": "2024-02-01T13:30:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "Sexo",
    "query": "SELECT DISTINCT SEXO FROM POBR;"
   },
   {
    "name": "Ano_Diagn",
    "label": "Ano do Diagnóstico",
    "query": "SELECT DISTINCT ANO_DIAGN FROM POBR ORDER BY ANO_DIAGN DESC"
   },
   {
    "name": "Estadiamento",
    "query": "SELECT DISTINCT ESTADIAM FROM POBR ORDER BY ESTADIAM"
   },
   {
    "name": "Tratamento",
    "query": "SELECT DISTINCT TRATAMENTO FROM POBR"
   },
   {
    "name": "Diag_Deth",
    "label": "Diagnóstico Detalhado",
    "query": "SELECT DISTINCT DIAG_DETH FROM POBR ORDER BY DIAG_DETH"
   },
   {
    "name": "Dados",
    "query": "SELECT ID FROM POBR WHERE SEXO IN ($Sexo) AND ANO_DIAGN IN ($Ano_Diagn) AND ESTADIAM IN ($Estadiamento) AND TRATAMENTO IN ($Tratamento) AND DIAG_DETH IN ($Diag_Deth)"
   }
  ]
 },
 "panels": [
  {
   "title": "Registros",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "DATASUS",
     "rawSql": "SELECT COUNT(*) FROM POBR WHERE ID IN ($Dados)"
    }
   ]
  },
  {
   "title": "Registros entre os Sexos",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "DATASUS",
     "rawSql": "SELECT SEXO, (COUNT(*) * 100.0 / (SELECT COUNT(*) FROM DATASUS.POBR)) AS Porcentagem\n  FROM DATASUS.POBR\n  WHERE ID IN ($Dados)\n GROUP BY SEXO;\n"
    }
   ]
  },
  {
   "title": "Estadiamento Médio",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "DATASUS",
     "rawSql": "SELECT AVG(subquery.ESTADIAM_NUMERIC) AS average_estadiam_numeric\nFROM (\n    SELECT \n        CASE ESTADIAM\n            WHEN '0' THEN 0\n            WHEN 'I' THEN 1\n            WHEN 'II' THEN 2\n            WHEN 'III' THEN 3\n            WHEN 'IV' THEN 4\n        END AS ESTADIAM_NUMERIC\n    FROM POBR\n    WHERE ESTADIAM != '9' AND ESTADIAM != '5'\n      AND ID IN ($Dados)\n) AS subquery;\n"
    }
   ]
  },
  {
   "title": "Tempo entre Diagnóstico e Tratamento",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "DATASUS",
     "rawSql": "SELECT\n    MIN(days_diff) AS \"Mínimo\",\n    AVG(days_diff) AS \"Média\",\n    MAX(days_diff) AS \"Máximo\"\nFROM (\n    SELECT DATEDIFF(STR_TO_DATE(DT_TRAT, '%d/%m/%Y'), STR_TO_DATE(DT_DIAG, '%d/%m/%Y')) AS days_diff\n    FROM POBR\n    WHERE ID IN ($Dados)\n) AS subquery;"
    }
   ]
  },
  {
   "title": "Diagnóstico Detalhado",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "DATASUS",
     "rawSql": "SELECT DIAG_DETH, (COUNT(*) * 100.0 / (SELECT COUNT(*) FROM DATASUS.POBR)) AS Porcentagem\n  FROM DATASUS.POBR\n  WHERE ID IN ($Dados)\n GROUP BY DIAG_DETH;\n"
    }
   ]
  },
  {
   "title": "Registros por Idade",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "DATASUS",
     "rawSql": "SELECT CAST(IDADE AS CHAR) AS \"Idade\", COUNT(*) AS \"Quantidade\"\nFROM DATASUS.POBR\nWHERE POBR.IDADE < 999\n  AND ID IN ($Dados)\nGROUP BY POBR.IDADE\nORDER BY POBR.IDADE;\n"
    }
   ]
  },
  {
   "title": "Registros por Estadiamento",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "DATASUS",
     "rawSql": "SELECT CAST(ESTADIAM AS CHAR) AS \"Estadiamento\", COUNT(*) AS \"Quantidade\"\n  FROM POBR\n  WHERE ID IN ($Dados)\n  GROUP BY ESTADIAM\n  ORDER BY ESTADIAM"
    }
   ]
  },
  {
   "title": "Tipo de Tratamento por Idade",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "dataset": "DATASUS",
     "rawSql": "SELECT CONCAT(CAST(IDADE AS CHAR), \" y\") AS \"Idade\", TRATAMENTO AS \"Tratamento\", COUNT(*) AS \"Quantidade\"\nFROM DATASUS.POBR\nWHERE POBR.IDADE < 999\n  AND TRATAMENTO != 5\n  AND ID IN ($Dados)\nGROUP BY POBR.IDADE, TRATAMENTO\nORDER BY POBR.IDADE, TRATAMENTO;\n"
    }
   ]
  },
  {
   "title": "Categoria de Diagnóstico por Idade",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "dataset": "DATASUS",
     "rawSql": "SELECT CONCAT(CAST(IDADE AS CHAR), \" y\") AS \"Idade\", DIAGNOSTIC AS \"Categoria de Diagnóstico\", COUNT(*) AS \"Quantidade\"\nFROM DATASUS.POBR\nWHERE POBR.IDADE < 999\n  AND ID IN ($Dados)\nGROUP BY POBR.IDADE, DIAGNOSTIC\nORDER BY POBR.IDADE, DIAGNOSTIC;\n"
    }
   ]
  },
  {
   "title": "Registros por Ano",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "DATASUS",
     "rawSql": "SELECT DATE(CONCAT(ANO_DIAGN, '-01-02')) AS \"Ano do Diagnóstico\", COUNT(*) AS \"Quantidade\"\nFROM DATASUS.POBR\nWHERE ID IN ($Dados)\nGROUP BY POBR.ANO_DIAGN\nORDER BY POBR.ANO_DIAGN;\n"
    }
   ]
  },
  {
   "title": "Tempo Médio entre Diagnóstico e Tratamento por Estadiamento",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "targets": [
    {
     "dataset": "DATASUS",
     "rawSql": "SELECT CAST(ESTADIAM AS CHAR) AS Estadiamento, AVG(days_diff) AS \"Tempo Médio entre Diagnóstico e Tratamento\"\nFROM (\n    SELECT \n        ESTADIAM,\n        DATEDIFF(STR_TO_DATE(DT_TRAT, '%d/%m/%Y'), STR_TO_DATE(DT_DIAG, '%d/%m/%Y')) AS days_diff\n    FROM POBR\n    WHERE ESTADIAM != 'Ignorado'\n      AND ID IN ($Dados)\n) AS subquery\nGROUP BY ESTADIAM\nORDER BY ESTADIAM;\n"
    }
   ]
  },
  {
   "title": "Estadiamento por Idade",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "dataset": "DATASUS",
     "rawSql": "SELECT CONCAT(CAST(IDADE AS CHAR), \" y\") AS \"Idade\", ESTADIAM AS \"Estadiamento\", COUNT(*) AS \"Quantidade\"\nFROM DATASUS.POBR\nWHERE POBR.IDADE < 999\n  AND ESTADIAM != 'Ignorado'\n  AND ID IN ($Dados)\nGROUP BY POBR.IDADE, ESTADIAM\nORDER BY POBR.IDADE, ESTADIAM;\n"
    }
   ]
  }
 ]
}